# Default initial positions for delto_gripper_5f's ros2_control fake system

initial_positions:
  j_1_1: 0
  j_1_2: 0
  j_1_3: 0
  j_1_4: 0
  j_2_1: 0
  j_2_2: 0
  j_2_3: 0
  j_2_4: 0
  j_3_1: 0
  j_3_2: 0
  j_3_3: 0
  j_3_4: 0
  j_4_1: 0
  j_4_2: 0
  j_4_3: 0
  j_4_4: 0
  j_5_1: 0
  j_5_2: 0
  j_5_3: 0
  j_5_4: 0