# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - delto_5f_controller

  delto_5f_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - j_1_1
      - j_1_2
      - j_1_3
      - j_1_4
      - j_2_1
      - j_2_2
      - j_2_3
      - j_2_4
      - j_3_1
      - j_3_2
      - j_3_3
      - j_3_4
      - j_4_1
      - j_4_2
      - j_4_3
      - j_4_4
      - j_5_1
      - j_5_2
      - j_5_3
      - j_5_4