# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    delto_5f_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

delto_5f_controller:
  ros__parameters:
    joints:
      - j_1_1
      - j_1_2
      - j_1_3
      - j_1_4 
      - j_2_1
      - j_2_2
      - j_2_3
      - j_2_4
      - j_3_1
      - j_3_2
      - j_3_3
      - j_3_4
      - j_4_1
      - j_4_2
      - j_4_3
      - j_4_4
      - j_5_1
      - j_5_2
      - j_5_3
      - j_5_4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position