name: Build and Deploy Sphinx Docs (Clean Links, Check Size)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 저장소 체크아웃 & Python
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      # 2) Sphinx 빌드
      - name: Build Sphinx docs
        run: sphinx-build -b html docs/source docs/build/html

      # 3) 링크 제거 (cp -rL) + 압축/해제
      - name: Remove links & re-archive
        run: |
          echo "[INFO] Removing symlinks/hardlinks with cp -rL..."
          mkdir -p docs/build/final
          cp -rL docs/build/html/* docs/build/final

          echo "[INFO] Archiving final directory..."
          cd docs/build
          tar -cf final.tar final

          echo "[INFO] Remove old dirs..."
          rm -rf html final

          echo "[INFO] Extracting tar to a fresh html dir..."
          mkdir html
          tar -xf final.tar -C html --strip-components=1

          echo "[INFO] Done. Listing final output..."
          find html -ls
          du -sh html

      # 4) 디버그
      - name: Debug structure
        run: |
          echo "=== Check for symlinks ==="
          find docs/build/html -type l -exec ls -la {} \; || true

          echo "=== Check inodes ==="
          ls -aliR docs/build/html | sort | uniq -c | sort -nr | head -30

          echo "=== Check size ==="
          du -sh docs/build/html

      # (선택) Jekyll 무시파일
      - name: Create .nojekyll
        run: echo > docs/build/html/.nojekyll

      # 5) 아티팩트 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
