name: Build and Deploy Sphinx Docs (No Symlinks/Hardlinks)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      # ============================
      # 심/하드링크 제거 단계 시작
      # ============================
      - name: Convert symlinks/hardlinks to normal files (using rsync)
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          mkdir -p docs/build/cleaned_html
          rsync -a -L docs/build/html/ docs/build/cleaned_html/
          rm -rf docs/build/html
          mv docs/build/cleaned_html docs/build/html


      # ============================
      # 심/하드링크 제거 단계 끝
      # ============================

      - name: Upload artifact (github-pages)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
