name: Build and Deploy Sphinx Docs (Enhanced)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # 1. Checkout Repository & Set Up Python
      # -------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      # -------------------------
      # 2. Build Sphinx Documentation
      # -------------------------
      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      # -------------------------
      # 3. Remove Symlinks, Set Permissions, and Clean Artifacts
      # -------------------------
      - name: Remove symlinks and set permissions
        run: |
          echo "[INFO] Removing symlinks..."
          mkdir -p docs/build/final
          cp -rL docs/build/html/* docs/build/final
          rm -rf docs/build/html
          mv docs/build/final docs/build/html
          chmod -R a+rX docs/build/html
          echo "[INFO] Symlinks removed and permissions set."

      - name: Remove unnecessary files
        run: |
          echo "[INFO] Cleaning up unnecessary files..."
          find docs/build/html -name ".lock" -type f -exec rm -f {} \;
          find docs/build/html -name ".DS_Store" -type f -exec rm -f {} \;
          find docs/build/html -name ".git*" -exec rm -rf {} +
          echo "[INFO] Cleanup complete."

      - name: Ensure index.html exists
        run: |
          if [ ! -f docs/build/html/index.html ]; then
            echo "[ERROR] index.html is missing. Deployment cannot proceed."
            exit 1
          fi

      # -------------------------
      # 4. Upload Artifact
      # -------------------------
      - name: Upload artifact (github-pages)
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
